export const SCHEMA_VERSION = 6

export const SCHEMA_DDL = `
CREATE NODE TABLE IF NOT EXISTS File(
  path STRING,
  language STRING,
  contentHash STRING,
  workspace STRING,
  PRIMARY KEY (path)
);
CREATE NODE TABLE IF NOT EXISTS Symbol(
  id STRING,
  name STRING,
  searchName STRING,
  kind STRING,
  filePath STRING,
  line INT64,
  col INT64,
  comment STRING,
  PRIMARY KEY (id)
);
CREATE NODE TABLE IF NOT EXISTS Spec(
  specId STRING,
  path STRING,
  title STRING,
  description STRING,
  contentHash STRING,
  content STRING,
  workspace STRING,
  PRIMARY KEY (specId)
);
CREATE NODE TABLE IF NOT EXISTS Meta(
  key STRING,
  value STRING,
  PRIMARY KEY (key)
);
CREATE REL TABLE IF NOT EXISTS IMPORTS(FROM File TO File);
CREATE REL TABLE IF NOT EXISTS DEFINES(FROM File TO Symbol);
CREATE REL TABLE IF NOT EXISTS CALLS(FROM Symbol TO Symbol);
CREATE REL TABLE IF NOT EXISTS CONSTRUCTS(FROM Symbol TO Symbol);
CREATE REL TABLE IF NOT EXISTS USES_TYPE(FROM Symbol TO Symbol);
CREATE REL TABLE IF NOT EXISTS EXPORTS(FROM File TO Symbol);
CREATE REL TABLE IF NOT EXISTS DEPENDS_ON(FROM Spec TO Spec);
CREATE REL TABLE IF NOT EXISTS COVERS(FROM Spec TO File);
CREATE REL TABLE IF NOT EXISTS EXTENDS(FROM Symbol TO Symbol);
CREATE REL TABLE IF NOT EXISTS IMPLEMENTS(FROM Symbol TO Symbol);
CREATE REL TABLE IF NOT EXISTS OVERRIDES(FROM Symbol TO Symbol);
`
