// Bootstrap
export { createKernel, type Kernel, type KernelOptions } from '@specd/core'
export { createDefaultConfigLoader, type FsConfigLoaderOptions } from '@specd/core'
export { createConfigWriter, type FsConfigWriterOptions } from '@specd/core'
export { createVcsAdapter } from '@specd/core'
export { createVcsActorResolver } from '@specd/core'
export { createLogFormatter } from '@specd/core'
export { LogRingBuffer } from '@specd/core'
export type { ActorResolver } from '@specd/core'
export { createSchemaRegistry, type FsSchemaRegistryOptions } from '@specd/core'
export {
  createSchemaRepository,
  type SchemaRepositoryConfig,
  type FsSchemaRepositoryOptions,
} from '@specd/core'
export {
  createSpecRepository,
  type SpecRepositoryConfig,
  type FsSpecRepositoryOptions,
} from '@specd/core'
export {
  createChangeRepository,
  type ChangeRepositoryConfig,
  type FsChangeRepositoryOptions,
} from '@specd/core'
export {
  createArchiveRepository,
  type ArchiveRepositoryConfig,
  type FsArchiveRepositoryOptions,
} from '@specd/core'
export {
  type SpecdConfig,
  type SpecdApiAuthConfig,
  type SpecdGraphConfig,
  type SpecdWorkspaceConfig,
  type SpecdWorkspaceGraphConfig,
  type SpecdStorageConfig,
  type SpecdContextEntry,
  isSpecdConfig,
} from '@specd/core'
export { Logger } from '@specd/core'
export { TemplateExpander } from '@specd/core'
export type { SchemaRawResult } from '@specd/core'
export type { LogDestination, LogEntry, LogFormat, LogLevel, LoggerPort } from '@specd/core'
export type { ChangeRepository, SpecRepository, SchemaRegistry } from '@specd/core'

// Use-case types and helpers
export {
  type ListChanges,
  type ListDrafts,
  type ListDiscarded,
  type ListArchived,
  type GetArchivedChange,
  type GetArchivedChangeInput,
  type EditChange,
  type EditChangeInput,
  type EditChangeResult,
  type SkipArtifact,
  type SkipArtifactInput,
  type UpdateSpecDepsInput,
  type UpdateSpecDepsResult,
  type ListSpecs,
  type SpecListEntry,
  type SpecMetadataStatus,
  type SearchSpecs,
  type SpecSearchEntry,
  type SearchSpecsOptions,
  type SpecSearchMatch,
  type GetSpec,
  type GetSpecInput,
  type GetSpecResult,
  type SaveSpecMetadata,
  type SaveSpecMetadataInput,
  type SaveSpecMetadataResult,
  type InvalidateSpecMetadata,
  type InvalidateSpecMetadataInput,
  type InvalidateSpecMetadataResult,
  type GetActiveSchema,
  type GetActiveSchemaInput,
  type GetActiveSchemaOptions,
  type GetActiveSchemaResult,
  type GetActiveSchemaResolved,
  type GetActiveSchemaRaw,
  type ResolveSchema,
  type ValidateSchemaInput,
  type ValidateSchemaResult,
  type ListWorkspaces,
  type ProjectWorkspace,
  GetProjectSummary,
  type GetProjectSummaryResult,
  type GetProjectContext,
  type GetProjectContextInput,
  type GetProjectContextResult,
  GetConfig,
  type CreateChange,
  type CreateChangeInput,
  type GetStatus,
  type GetStatusInput,
  type GetStatusResult,
  type ArtifactStatusEntry,
  type LifecycleContext,
  type TransitionBlocker,
  type ReviewSummary,
  type ReviewOverlapEntry,
  type ImplementationTrackingProjection,
  type GetImplementationReviewInput,
  type GetImplementationReviewResult,
  type UpdateImplementationTrackingAction,
  type UpdateImplementationTrackingInput,
  type UpdateImplementationTrackingResult,
  type RefreshImplementationTrackingInput,
  type RefreshImplementationTrackingResult,
  type HookPhaseSelector,
  type TransitionChange,
  type TransitionChangeInput,
  type TransitionChangeResult,
  type TransitionProgressEvent,
  type OnTransitionProgress,
  type DraftChange,
  type DraftChangeInput,
  type GetDraft,
  type GetDraftInput,
  type GetDraftResult,
  type GetDiscarded,
  type GetDiscardedInput,
  type GetDiscardedResult,
  type RestoreChange,
  type RestoreChangeInput,
  type DiscardChange,
  type DiscardChangeInput,
  type ApproveSpec,
  type ApproveSpecInput,
  type ApproveSignoff,
  type ApproveSignoffInput,
  type GetChangeArtifactInput,
  type GetChangeArtifactResult,
  type SaveChangeArtifactInput,
  type SaveChangeArtifactResult,
  type ValidateChangeBatchInput,
  type ValidateChangeBatchResult,
  type ValidateChangeBatchStepResult,
  type ArchiveHookPhaseSelector,
  type ArchiveChange,
  type ArchiveChangeInput,
  type ArchiveChangeResult,
  type InvalidatedChangesEntry,
  type ValidateArtifacts,
  type ValidateArtifactsInput,
  type ValidateArtifactsResult,
  type ValidationFailure,
  type ValidationFileResult,
  type ValidationFileStatus,
  type ValidationWarning,
  type CompileContext,
  type CompileContextInput,
  type CompileContextResult,
  type CompileContextConfig,
  type ContextEntry,
  type WorkspaceContextConfig,
  type ContextWarning,
  type ContextSpecEntry,
  type ContextSpecSource,
  type ProjectContextEntry,
  type AvailableStep,
  type SpecSection,
  checkMetadataFreshness,
  type ContentHashEntry,
  type MetadataFreshnessResult,
  computeArtifactHash,
  buildCleanupMap,
  parseMetadata,
  type GenerateSpecMetadataInput,
  type GenerateSpecMetadataResult,
  type GetSpecContext,
  type GetSpecContextInput,
  type GetSpecContextResult,
  type SpecContextEntry,
  type SpecContextSectionFlag,
  type ValidateSpecs,
  type ValidateSpecsInput,
  type ValidateSpecsResult,
  type SpecValidationEntry,
  type RunStepHooksInput,
  type RunStepHooksResult,
  type RunStepHookEntry,
  type HookProgressEvent,
  type OnHookProgress,
  type GetHookInstructionsInput,
  type GetHookInstructionsResult,
  type DetectOverlap,
  type DetectOverlapInput,
  type GetArtifactInstructionInput,
  type GetArtifactInstructionResult,
  type PreviewSpec,
  type PreviewSpecInput,
  type PreviewSpecResult,
  type PreviewSpecFileEntry,
  type InvalidateChange,
  type InvalidateTargetInput,
  type InvalidateChangeInput,
  type AffectedArtifactFile,
  type InvalidateChangeResult,
  type GetSpecOutline,
  type GetSpecOutlineInput,
  type SpecOutlineResult,
  type UpdateSpecMetadata,
  type UpdateSpecMetadataInput,
  type UpdateSpecMetadataResult,
  type GetProjectMetadata,
  type GetProjectMetadataResult,
  type UpdateProjectMetadata,
  type UpdateProjectMetadataInput,
  type UpdateProjectMetadataResult,
} from '@specd/core'

export { NodeContentHasher } from '@specd/core'

// Composition factories
export {
  createListChanges,
  type ListChangesDeps,
  createListDrafts,
  type ListDraftsDeps,
  createListDiscarded,
  type ListDiscardedDeps,
  createListArchived,
  type ListArchivedDeps,
  createGetArchivedChange,
  type GetArchivedChangeDeps,
  createEditChange,
  type EditChangeDeps,
  createSkipArtifact,
  type SkipArtifactDeps,
  createListSpecs,
  type ListSpecsDeps,
  createListWorkspaces,
  type ListWorkspacesDeps,
  createGetProjectSummary,
  createSearchSpecs,
  type SearchSpecsDeps,
  createGetSpec,
  type GetSpecDeps,
  createSaveSpecMetadata,
  type SaveSpecMetadataDeps,
  createInvalidateSpecMetadata,
  type InvalidateSpecMetadataDeps,
  createGetActiveSchema,
  type GetActiveSchemaDeps,
  createGetProjectContext,
  type GetProjectContextDeps,
  createGetConfig,
  type GetConfigDeps,
  createCreateChange,
  type CreateChangeDeps,
  createGetStatus,
  type GetStatusDeps,
  createTransitionChange,
  type TransitionChangeDeps,
  createDraftChange,
  type DraftChangeDeps,
  createRestoreChange,
  type RestoreChangeDeps,
  createDiscardChange,
  type DiscardChangeDeps,
  createApproveSpec,
  type ApproveSpecDeps,
  createApproveSignoff,
  type ApproveSignoffDeps,
  createArchiveChange,
  type ArchiveChangeDeps,
  createValidateArtifacts,
  type ValidateArtifactsDeps,
  createCompileContext,
  type CompileContextDeps,
  createValidateSpecs,
  type ValidateSpecsDeps,
  createGetSpecContext,
  type GetSpecContextDeps,
  createDetectOverlap,
  type DetectOverlapDeps,
  createPreviewSpec,
  type PreviewSpecDeps,
  createResolveSchema,
  type ResolveSchemaDeps,
  createUpdateSpecDeps,
  type UpdateSpecDepsDeps,
  createInvalidateChange,
  type InvalidateChangeDeps,
  createRunStepHooks,
  type RunStepHooksDeps,
  createGetHookInstructions,
  type GetHookInstructionsDeps,
  createGetArtifactInstruction,
  type GetArtifactInstructionDeps,
  createUpdateImplementationTracking,
  type UpdateImplementationTrackingDeps,
  createRefreshImplementationTracking,
  type RefreshImplementationTrackingDeps,
  createGetImplementationReview,
  type GetImplementationReviewDeps,
  createGetSpecOutline,
  type GetSpecOutlineDeps,
  createValidateSchema,
  type ValidateSchemaDeps,
  createGenerateSpecMetadata,
  createUpdateSpecMetadata,
  createGetProjectMetadata,
  createUpdateProjectMetadata,
} from '@specd/core'
export { createGetDraft } from '@specd/core'
export { createGetDiscarded } from '@specd/core'

// Application errors
export {
  ChangeNotFoundError,
  ChangeAlreadyExistsError,
  InvalidCreateChangeInputError,
  ApprovalGateDisabledError,
  SchemaNotFoundError,
  AlreadyInitialisedError,
  SpecNotInChangeError,
  ArtifactNotFoundError,
  ParserNotRegisteredError,
  ExternalHookTypeNotRegisteredError,
  SchemaMismatchError,
  SpecNotFoundError,
  WorkspaceNotFoundError,
  InvalidInvalidateTargetError,
  InvalidateRequiresForceError,
  ImplementationLinksExistError,
  ImplementationFileNotFoundError,
  ConfigNotFoundError,
  ProjectMetadataNotFoundError,
  UiPluginNotConfiguredError,
  UiPluginTypeMismatchError,
} from '@specd/core'

// Domain entities
export {
  Change,
  type ChangeProps,
  type ActorIdentity,
  type ChangeEvent,
  type CreatedEvent,
  type TransitionedEvent,
  type SpecApprovedEvent,
  type SignedOffEvent,
  type InvalidatedEvent,
  type DraftedEvent,
  type RestoredEvent,
  type DiscardedEvent,
  type ArtifactSkippedEvent,
  type ArtifactsSyncedEvent,
  SYSTEM_ACTOR,
  Spec,
  ChangeArtifact,
  SKIPPED_SENTINEL,
  type ChangeArtifactProps,
  Delta,
  type DeltaProps,
  type ArchivedChange,
} from '@specd/core'

// Domain value objects
export {
  ArtifactFile,
  ARTIFACT_FILE_SKIPPED_SENTINEL,
  type ArtifactFileProps,
  DomainPath,
  SpecPath,
  SpecArtifact,
  type ChangeState,
  VALID_TRANSITIONS,
  isValidTransition,
  type ArtifactStatus,
  type ArtifactDisplayStatus,
  type InvalidationPolicy,
  DEFAULT_INVALIDATION_POLICY,
  isInvalidationPolicy,
  type Selector,
  type DeltaPosition,
  type ValidationCount,
  type CrossArtifactScope,
  type CrossArtifactKeySource,
  type CrossArtifactRelationKind,
  type CrossArtifactOrdering,
  type CrossArtifactKeySpec,
  type CrossArtifactParticipant,
  type CrossArtifactRelation,
  type CrossArtifactValidationRule,
  type Extractor,
  type ExtractorTransformDeclaration,
  type FieldMapping,
  type MetadataExtraction,
  type MetadataExtractorEntry,
  type ValidationRule,
  type PreHashCleanup,
  type TaskCompletionCheck,
  type HookEntry,
  type WorkflowStep,
  HookResult,
  ArtifactType,
  type ArtifactTypeProps,
  type ArtifactScope,
  type ArtifactFormat,
  type RuleEntry,
  type ArtifactRules,
  ArtifactDag,
  artifactDagFromChangeArtifacts,
  Schema,
  type SchemaKind,
  OverlapEntry,
  type OverlapChange,
  OverlapReport,
} from '@specd/core'

// Domain errors
export {
  SpecdError,
  InvalidStateTransitionError,
  type TransitionFailureReason,
  ApprovalRequiredError,
  InvalidSpecPathError,
  ArtifactConflictError,
  ArtifactNotOptionalError,
  HookFailedError,
  SchemaValidationError,
  ConfigValidationError,
  DeltaApplicationError,
  UnsupportedPatternError,
  CorruptedManifestError,
  PathTraversalError,
  ReadOnlyWorkspaceError,
  ArtifactParseError,
  MetadataValidationError,
  ExtractorTransformError,
  DependsOnOverwriteError,
  InvalidChangeError,
  MissingDefaultWorkspaceError,
  StepNotValidError,
  HookNotFoundError,
  SpecOverlapError,
  SpecPublicationError,
  ArchiveDependencyMismatchError,
  ArchiveArtifactMissingError,
  ArchiveImplementationStateError,
  HistoricalImplementationGuardError,
  type GuardedChangeOperation,
  InvalidInputError,
  DraftedChangeReadOnlyError,
} from '@specd/core'

export {
  type ReadOnlyChangeView,
  type DraftedChangeView,
  type DiscardedChangeView,
  type ArchivedChangeMeta,
  toDraftedChangeView,
  toDiscardedChangeView,
  toArchivedChangeView,
} from '@specd/core'
export { type ArchivedChangeIndexEntry, workspacesFromSpecIds } from '@specd/core'

// Domain services
export { applyPreHashCleanup } from '@specd/core'
export { expectedArtifactFilename, type ExpectedArtifactFilenameInput } from '@specd/core'
export { hashFiles } from '@specd/core'
export {
  projectMetadataSchema,
  updateProjectMetadataSchema,
  type ProjectMetadata,
  type UpdateProjectMetadataPayload,
} from '@specd/core'
export { specMetadataSchema, strictSpecMetadataSchema, type SpecMetadata } from '@specd/core'
export {
  parseSpecLock,
  specLockSchema,
  type SpecLockData,
  type SpecLockImplementationEntry,
} from '@specd/core'
export { parseSpecId } from '@specd/core'
export { extractSpecSummary } from '@specd/core'
export { inferFormat } from '@specd/core'
export { safeRegex } from '@specd/core'
export { shiftHeadings } from '@specd/core'
export {
  extractContent,
  type ExtractorTransformResult,
  type ExtractorTransform,
  type ExtractorTransformContext,
  type ExtractorTransformRegistry,
  type SubtreeRenderer,
  type GroupedExtraction,
  type StructuredExtraction,
} from '@specd/core'
export { extractMetadata, type ExtractedMetadata } from '@specd/core'
export {
  buildSchema,
  buildSelector,
  type SchemaYamlData,
  type ArtifactYamlData,
  type SelectorRaw,
  type ValidationRuleRaw,
  type CrossArtifactValidationRuleRaw,
  type CrossArtifactParticipantRaw,
  type CrossArtifactRelationRaw,
  type MetadataExtractionRaw,
  type RuleEntryRaw,
  type ArtifactRulesRaw,
} from '@specd/core'
export {
  mergeSchemaLayers,
  type SchemaLayer,
  type SchemaLayerSource,
  type SchemaOperations,
} from '@specd/core'
export {
  type SelectorNode,
  findNodes,
  nodeMatches,
  collectAll,
  selectBySelector,
  collectAllNodes,
} from '@specd/core'
export {
  evaluateCrossArtifactRule,
  type CrossArtifactEvaluationFailure,
  type CrossArtifactEvaluationWarning,
  type CrossArtifactParticipantInput,
  type CrossArtifactEvaluationContext,
  type CrossArtifactEvaluationResult,
} from '@specd/core'
export {
  evaluateRules,
  selectNodes,
  collectNodes,
  selectByJsonPath,
  tokenizeJsonPath,
  recursiveCollect,
  type RuleEvaluationFailure,
  type RuleEvaluationWarning,
  type RuleEvaluationResult,
  type RuleEvaluatorNode,
  type RuleEvaluatorParser,
} from '@specd/core'
export { detectSpecOverlap } from '@specd/core'
export {
  LifecycleEngine,
  type LifecycleEngineOptions,
  type LifecycleAffectedFile,
  type LifecycleAffectedArtifact,
  type LifecycleBlocker,
  type LifecycleReviewOverlapEntry,
  type LifecycleReviewSummary,
  type LifecycleNextAction,
  type LifecycleArtifactVerdict,
  type LifecycleTransitionBlocker,
  type LifecycleStepVerdict,
  type LifecycleVerdict,
} from '@specd/core'

export { CORE_VERSION } from '@specd/core'
