import { createRequire } from 'module'

// Bootstrap
export { createKernel, type Kernel, type KernelOptions } from './composition/kernel.js'
export { createLogFormatter } from './composition/create-log-formatter.js'
export { LogRingBuffer } from './infrastructure/logging/log-ring-buffer.js'
export { createConfigLoader, type FsConfigLoaderOptions } from './composition/config-loader.js'
export { createConfigWriter, type FsConfigWriterOptions } from './composition/config-writer.js'
export { createVcsAdapter } from './composition/vcs-adapter.js'
export { createVcsActorResolver } from './composition/actor-resolver.js'
export {
  createSchemaRegistry,
  type FsSchemaRegistryOptions,
} from './composition/schema-registry.js'
export {
  createSchemaRepository,
  type SchemaRepositoryConfig,
  type FsSchemaRepositoryOptions,
} from './composition/schema-repository.js'
export {
  createSpecRepository,
  type SpecRepositoryConfig,
  type FsSpecRepositoryOptions,
} from './composition/spec-repository.js'
export {
  createChangeRepository,
  type ChangeRepositoryConfig,
  type FsChangeRepositoryOptions,
} from './composition/change-repository.js'
export {
  createArchiveRepository,
  type ArchiveRepositoryConfig,
  type FsArchiveRepositoryOptions,
} from './composition/archive-repository.js'
export {
  type SpecdConfig,
  type SpecdGraphConfig,
  type SpecdApiAuthConfig,
  type SpecdApiConfig,
  type SpecdWorkspaceConfig,
  type SpecdWorkspaceGraphConfig,
  type SpecdStorageConfig,
  type SpecdContextEntry,
  isSpecdConfig,
} from './application/specd-config.js'
export { Logger } from './application/logger.js'
export { TemplateExpander } from './application/template-expander.js'
export type { SchemaRawResult } from './application/ports/schema-registry.js'
export type {
  LogDestination,
  LogEntry,
  LogFormat,
  LogLevel,
  LoggerPort,
} from './application/ports/logger.port.js'
export type { ChangeRepository, SpecRepository, SchemaRegistry } from './application/ports/index.js'
export type { ActorResolver } from './application/ports/actor-resolver.js'

// Use-case types and helpers
export {
  type ListChanges,
  type ListDrafts,
  type ListDiscarded,
  type ListArchived,
  type GetArchivedChange,
  type GetArchivedChangeInput,
  type EditChange,
  type EditChangeInput,
  type EditChangeResult,
  type SkipArtifact,
  type SkipArtifactInput,
  type UpdateSpecDepsInput,
  type UpdateSpecDepsResult,
  type ListSpecs,
  type SpecListEntry,
  type SpecMetadataStatus,
  type SearchSpecs,
  type SpecSearchEntry,
  type SearchSpecsOptions,
  type SpecSearchMatch,
  type GetSpec,
  type GetSpecInput,
  type GetSpecResult,
  type SaveSpecMetadata,
  type SaveSpecMetadataInput,
  type SaveSpecMetadataResult,
  type InvalidateSpecMetadata,
  type InvalidateSpecMetadataInput,
  type InvalidateSpecMetadataResult,
  type GetActiveSchema,
  type GetActiveSchemaInput,
  type GetActiveSchemaOptions,
  type GetActiveSchemaResult,
  type GetActiveSchemaResolved,
  type GetActiveSchemaRaw,
  type ResolveSchema,
  type ValidateSchemaInput,
  type ValidateSchemaResult,
  type ListWorkspaces,
  type ProjectWorkspace,
  GetProjectSummary,
  type GetProjectSummaryResult,
  type GetProjectContext,
  type GetProjectContextInput,
  type GetProjectContextResult,
  GetConfig,
  type CreateChange,
  type CreateChangeInput,
  type GetStatus,
  type GetStatusInput,
  type GetStatusResult,
  type ArtifactStatusEntry,
  type LifecycleContext,
  type TransitionBlocker,
  type ReviewSummary,
  type ReviewOverlapEntry,
  type ImplementationTrackingProjection,
  type GetImplementationReviewInput,
  type GetImplementationReviewResult,
  type UpdateImplementationTrackingAction,
  type UpdateImplementationTrackingInput,
  type UpdateImplementationTrackingResult,
  type RefreshImplementationTrackingInput,
  type RefreshImplementationTrackingResult,
  type HookPhaseSelector,
  type TransitionChange,
  type TransitionChangeInput,
  type TransitionChangeResult,
  type TransitionProgressEvent,
  type OnTransitionProgress,
  type DraftChange,
  type DraftChangeInput,
  type GetDraft,
  type GetDraftInput,
  type GetDraftResult,
  type GetDiscarded,
  type GetDiscardedInput,
  type GetDiscardedResult,
  type RestoreChange,
  type RestoreChangeInput,
  type DiscardChange,
  type DiscardChangeInput,
  type ApproveSpec,
  type ApproveSpecInput,
  type ApproveSignoff,
  type ApproveSignoffInput,
  type GetChangeArtifactInput,
  type GetChangeArtifactResult,
  type SaveChangeArtifactInput,
  type SaveChangeArtifactResult,
  type ValidateChangeBatchInput,
  type ValidateChangeBatchResult,
  type ValidateChangeBatchStepResult,
  type ArchiveHookPhaseSelector,
  type ArchiveChange,
  type ArchiveChangeInput,
  type ArchiveChangeResult,
  type InvalidatedChangesEntry,
  type ValidateArtifacts,
  type ValidateArtifactsInput,
  type ValidateArtifactsResult,
  type ValidationFailure,
  type ValidationFileResult,
  type ValidationFileStatus,
  type ValidationWarning,
  type CompileContext,
  type CompileContextInput,
  type CompileContextResult,
  type CompileContextConfig,
  type ContextEntry,
  type WorkspaceContextConfig,
  type ContextWarning,
  type ContextSpecEntry,
  type ContextSpecSource,
  type ProjectContextEntry,
  type AvailableStep,
  type SpecSection,
  checkMetadataFreshness,
  type ContentHashEntry,
  type MetadataFreshnessResult,
  computeArtifactHash,
  buildCleanupMap,
  parseMetadata,
  type GenerateSpecMetadataInput,
  type GenerateSpecMetadataResult,
  type GetSpecContext,
  type GetSpecContextInput,
  type GetSpecContextResult,
  type SpecContextEntry,
  type SpecContextSectionFlag,
  type ValidateSpecs,
  type ValidateSpecsInput,
  type ValidateSpecsResult,
  type SpecValidationEntry,
  type RunStepHooksInput,
  type RunStepHooksResult,
  type RunStepHookEntry,
  type HookProgressEvent,
  type OnHookProgress,
  type GetHookInstructionsInput,
  type GetHookInstructionsResult,
  type DetectOverlap,
  type DetectOverlapInput,
  type GetArtifactInstructionInput,
  type GetArtifactInstructionResult,
  type PreviewSpec,
  type PreviewSpecInput,
  type PreviewSpecResult,
  type PreviewSpecFileEntry,
  type InvalidateChange,
  type InvalidateTargetInput,
  type InvalidateChangeInput,
  type AffectedArtifactFile,
  type InvalidateChangeResult,
  type GetSpecOutline,
  type GetSpecOutlineInput,
  type SpecOutlineResult,
  type UpdateSpecMetadata,
  type UpdateSpecMetadataInput,
  type UpdateSpecMetadataResult,
  type GetProjectMetadata,
  type GetProjectMetadataResult,
  type UpdateProjectMetadata,
  type UpdateProjectMetadataInput,
  type UpdateProjectMetadataResult,
} from './application/use-cases/index.js'

export { NodeContentHasher } from './infrastructure/node/content-hasher.js'

// Composition factories
export {
  createListChanges,
  type ListChangesContext,
  type FsListChangesOptions,
  createListDrafts,
  type ListDraftsContext,
  type FsListDraftsOptions,
  createListDiscarded,
  type ListDiscardedContext,
  type FsListDiscardedOptions,
  createListArchived,
  type ListArchivedContext,
  type FsListArchivedOptions,
  createGetArchivedChange,
  type GetArchivedChangeContext,
  type FsGetArchivedChangeOptions,
  createEditChange,
  type EditChangeContext,
  type FsEditChangeOptions,
  createSkipArtifact,
  type SkipArtifactContext,
  type FsSkipArtifactOptions,
  createListSpecs,
  type FsListSpecsOptions,
  createListWorkspaces,
  type FsListWorkspacesOptions,
  createGetProjectSummary,
  createSearchSpecs,
  type FsSearchSpecsOptions,
  createGetSpec,
  type FsGetSpecOptions,
  createSaveSpecMetadata,
  type FsSaveSpecMetadataOptions,
  createInvalidateSpecMetadata,
  type FsInvalidateSpecMetadataOptions,
  createGetActiveSchema,
  type FsGetActiveSchemaOptions,
  createGetProjectContext,
  type FsGetProjectContextOptions,
  createGetConfig,
  type GetConfigOptions,
  createCreateChange,
  type CreateChangeContext,
  type FsCreateChangeOptions,
  createGetStatus,
  type GetStatusContext,
  type FsGetStatusOptions,
  createTransitionChange,
  type TransitionChangeContext,
  type FsTransitionChangeOptions,
  createDraftChange,
  type DraftChangeContext,
  type FsDraftChangeOptions,
  createRestoreChange,
  type RestoreChangeContext,
  type FsRestoreChangeOptions,
  createDiscardChange,
  type DiscardChangeContext,
  type FsDiscardChangeOptions,
  createApproveSpec,
  type ApproveSpecContext,
  type FsApproveSpecOptions,
  createApproveSignoff,
  type ApproveSignoffContext,
  type FsApproveSignoffOptions,
  createArchiveChange,
  type ArchiveChangeContext,
  type FsArchiveChangeOptions,
  createValidateArtifacts,
  type ValidateArtifactsContext,
  type FsValidateArtifactsOptions,
  createCompileContext,
  type CompileContextWorkspace,
  type FsCompileContextOptions,
  createValidateSpecs,
  type FsValidateSpecsOptions,
  createGetSpecContext,
  type FsGetSpecContextOptions,
  createDetectOverlap,
  type DetectOverlapContext,
  type FsDetectOverlapOptions,
  createPreviewSpec,
  type PreviewSpecWorkspace,
  type FsPreviewSpecOptions,
  createResolveSchema,
  type FsResolveSchemaOptions,
  createUpdateSpecDeps,
  type UpdateSpecDepsContext,
  type FsUpdateSpecDepsOptions,
  createInvalidateChange,
  type InvalidateChangeContext,
  type FsInvalidateChangeOptions,
  createRunStepHooks,
  type RunStepHooksContext,
  type FsRunStepHooksOptions,
  createGetHookInstructions,
  type GetHookInstructionsContext,
  type FsGetHookInstructionsOptions,
  createGetArtifactInstruction,
  type GetArtifactInstructionContext,
  type FsGetArtifactInstructionOptions,
  createUpdateImplementationTracking,
  type UpdateImplementationTrackingContext,
  type FsUpdateImplementationTrackingOptions,
  createRefreshImplementationTracking,
  type RefreshImplementationTrackingContext,
  type FsRefreshImplementationTrackingOptions,
  createGetImplementationReview,
  type GetImplementationReviewContext,
  type FsGetImplementationReviewOptions,
  createGetSpecOutline,
  type FsGetSpecOutlineOptions,
  createValidateSchema,
  type FsValidateSchemaOptions,
  createGenerateSpecMetadata,
  createUpdateSpecMetadata,
  createGetProjectMetadata,
  createUpdateProjectMetadata,
  createGetChangeArtifact,
  createGetReadOnlyChangeArtifact,
  type FsGetReadOnlyChangeArtifactOptions,
  createSaveChangeArtifact,
  type SaveChangeArtifactContext,
  type FsSaveChangeArtifactOptions,
  createValidateChangeBatch,
  createOutlineChangeArtifact,
  createReadLog,
} from './composition/use-cases/index.js'
export { createGetDraft } from './composition/use-cases/get-draft.js'
export { createGetDiscarded } from './composition/use-cases/get-discarded.js'

// Application errors
export {
  ChangeNotFoundError,
  ChangeAlreadyExistsError,
  InvalidCreateChangeInputError,
  ApprovalGateDisabledError,
  SchemaNotFoundError,
  AlreadyInitialisedError,
  SpecNotInChangeError,
  ArtifactNotFoundError,
  ParserNotRegisteredError,
  ExternalHookTypeNotRegisteredError,
  SchemaMismatchError,
  SpecNotFoundError,
  WorkspaceNotFoundError,
  InvalidInvalidateTargetError,
  InvalidateRequiresForceError,
  ImplementationLinksExistError,
  ImplementationFileNotFoundError,
  ConfigNotFoundError,
  ProjectMetadataNotFoundError,
  UiPluginNotConfiguredError,
  UiPluginTypeMismatchError,
  UiPluginBundleMissingError,
} from './application/errors/index.js'

// Domain entities
export {
  Change,
  type ChangeProps,
  type ActorIdentity,
  type ChangeEvent,
  type CreatedEvent,
  type TransitionedEvent,
  type SpecApprovedEvent,
  type SignedOffEvent,
  type InvalidatedEvent,
  type DraftedEvent,
  type RestoredEvent,
  type DiscardedEvent,
  type ArtifactSkippedEvent,
  type ArtifactsSyncedEvent,
  SYSTEM_ACTOR,
  Spec,
  ChangeArtifact,
  SKIPPED_SENTINEL,
  type ChangeArtifactProps,
  Delta,
  type DeltaProps,
  type ArchivedChange,
} from './domain/entities/index.js'

// Domain value objects
export {
  ArtifactFile,
  ARTIFACT_FILE_SKIPPED_SENTINEL,
  type ArtifactFileProps,
  DomainPath,
  SpecPath,
  SpecArtifact,
  type ChangeState,
  VALID_TRANSITIONS,
  isValidTransition,
  type ArtifactStatus,
  type ArtifactDisplayStatus,
  type InvalidationPolicy,
  DEFAULT_INVALIDATION_POLICY,
  isInvalidationPolicy,
  type Selector,
  type DeltaPosition,
  type ValidationCount,
  type CrossArtifactScope,
  type CrossArtifactKeySource,
  type CrossArtifactRelationKind,
  type CrossArtifactOrdering,
  type CrossArtifactKeySpec,
  type CrossArtifactParticipant,
  type CrossArtifactRelation,
  type CrossArtifactValidationRule,
  type Extractor,
  type ExtractorTransformDeclaration,
  type FieldMapping,
  type MetadataExtraction,
  type MetadataExtractorEntry,
  type ValidationRule,
  type PreHashCleanup,
  type TaskCompletionCheck,
  type HookEntry,
  type WorkflowStep,
  HookResult,
  ArtifactType,
  type ArtifactTypeProps,
  type ArtifactScope,
  type ArtifactFormat,
  type RuleEntry,
  type ArtifactRules,
  ArtifactDag,
  artifactDagFromChangeArtifacts,
  Schema,
  type SchemaKind,
  OverlapEntry,
  type OverlapChange,
  OverlapReport,
} from './domain/value-objects/index.js'

// Domain errors
export {
  SpecdError,
  InvalidStateTransitionError,
  type TransitionFailureReason,
  ApprovalRequiredError,
  InvalidSpecPathError,
  ArtifactConflictError,
  ArtifactNotOptionalError,
  HookFailedError,
  SchemaValidationError,
  ConfigValidationError,
  DeltaApplicationError,
  UnsupportedPatternError,
  CorruptedManifestError,
  PathTraversalError,
  ReadOnlyWorkspaceError,
  ArtifactParseError,
  MetadataValidationError,
  ExtractorTransformError,
  DependsOnOverwriteError,
  InvalidChangeError,
  MissingDefaultWorkspaceError,
  StepNotValidError,
  HookNotFoundError,
  SpecOverlapError,
  SpecPublicationError,
  ArchiveDependencyMismatchError,
  ArchiveArtifactMissingError,
  ArchiveImplementationStateError,
  HistoricalImplementationGuardError,
  type GuardedChangeOperation,
  InvalidInputError,
  DraftedChangeReadOnlyError,
} from './domain/errors/index.js'

export {
  type ReadOnlyChangeView,
  type DraftedChangeView,
  type DiscardedChangeView,
  type ArchivedChangeMeta,
  toDraftedChangeView,
  toDiscardedChangeView,
  toArchivedChangeView,
} from './domain/read-only-change-view.js'
export {
  type ArchivedChangeIndexEntry,
  workspacesFromSpecIds,
} from './domain/archived-change-index-entry.js'

// Domain services
export { applyPreHashCleanup } from './domain/services/pre-hash-cleanup.js'
export {
  expectedArtifactFilename,
  type ExpectedArtifactFilenameInput,
} from './domain/services/artifact-filename.js'
export { hashFiles } from './domain/services/hash-files.js'
export {
  projectMetadataSchema,
  updateProjectMetadataSchema,
  type ProjectMetadata,
  type UpdateProjectMetadataPayload,
} from './domain/services/project-metadata.js'
export {
  specMetadataSchema,
  strictSpecMetadataSchema,
  type SpecMetadata,
} from './domain/services/parse-metadata.js'
export {
  parseSpecLock,
  specLockSchema,
  type SpecLockData,
  type SpecLockImplementationEntry,
} from './domain/services/parse-spec-lock.js'
export { parseSpecId } from './domain/services/parse-spec-id.js'
export { extractSpecSummary } from './domain/services/spec-summary.js'
export { inferFormat } from './domain/services/format-inference.js'
export { safeRegex } from './domain/services/safe-regex.js'
export { shiftHeadings } from './domain/services/shift-headings.js'
export {
  extractContent,
  type ExtractorTransformResult,
  type ExtractorTransform,
  type ExtractorTransformContext,
  type ExtractorTransformRegistry,
  type SubtreeRenderer,
  type GroupedExtraction,
  type StructuredExtraction,
} from './domain/services/content-extraction.js'
export { extractMetadata, type ExtractedMetadata } from './domain/services/extract-metadata.js'
export {
  buildSchema,
  buildSelector,
  type SchemaYamlData,
  type ArtifactYamlData,
  type SelectorRaw,
  type ValidationRuleRaw,
  type CrossArtifactValidationRuleRaw,
  type CrossArtifactParticipantRaw,
  type CrossArtifactRelationRaw,
  type MetadataExtractionRaw,
  type RuleEntryRaw,
  type ArtifactRulesRaw,
} from './domain/services/build-schema.js'
export {
  mergeSchemaLayers,
  type SchemaLayer,
  type SchemaLayerSource,
  type SchemaOperations,
} from './domain/services/merge-schema-layers.js'
export {
  type SelectorNode,
  findNodes,
  nodeMatches,
  collectAll,
  selectBySelector,
  collectAllNodes,
} from './domain/services/selector-matching.js'
export {
  evaluateCrossArtifactRule,
  type CrossArtifactEvaluationFailure,
  type CrossArtifactEvaluationWarning,
  type CrossArtifactParticipantInput,
  type CrossArtifactEvaluationContext,
  type CrossArtifactEvaluationResult,
} from './domain/services/cross-artifact-rule-evaluator.js'
export {
  evaluateRules,
  selectNodes,
  collectNodes,
  selectByJsonPath,
  tokenizeJsonPath,
  recursiveCollect,
  type RuleEvaluationFailure,
  type RuleEvaluationWarning,
  type RuleEvaluationResult,
  type RuleEvaluatorNode,
  type RuleEvaluatorParser,
} from './domain/services/rule-evaluator.js'
export { detectSpecOverlap } from './domain/services/detect-spec-overlap.js'
export {
  LifecycleEngine,
  type LifecycleEngineOptions,
  type LifecycleAffectedFile,
  type LifecycleAffectedArtifact,
  type LifecycleBlocker,
  type LifecycleReviewOverlapEntry,
  type LifecycleReviewSummary,
  type LifecycleNextAction,
  type LifecycleArtifactVerdict,
  type LifecycleTransitionBlocker,
  type LifecycleStepVerdict,
  type LifecycleVerdict,
} from './domain/services/lifecycle-engine.js'

const _require = createRequire(import.meta.url)
/** Installed version of `@specd/core`. */
export const CORE_VERSION: string = (_require('../package.json') as { version: string }).version
