export {
  evaluateRules,
  selectNodes,
  selectBySelector,
  nodeMatches,
  collectNodes,
  selectByJsonPath,
  tokenizeJsonPath,
  recursiveCollect,
  type RuleEvaluationFailure,
  type RuleEvaluationWarning,
  type RuleEvaluationResult,
  type RuleEvaluatorNode,
  type RuleEvaluatorParser,
} from './rule-evaluator.js'
