import { describe, expect, it } from 'vitest'
import apiSidebars from '../../api-sidebars'
import sidebars from '../../sidebars'

interface SidebarCategoryShape {
  readonly type: 'category'
  readonly label: string
  readonly items: readonly unknown[]
}

function isSidebarCategoryShape(value: unknown): value is SidebarCategoryShape {
  if (!value || typeof value !== 'object') {
    return false
  }

  const candidate = value as Partial<SidebarCategoryShape>
  return (
    candidate.type === 'category' &&
    typeof candidate.label === 'string' &&
    Array.isArray(candidate.items)
  )
}

describe('sidebar configuration', () => {
  it('keeps the public docs sidebar organized into deliberate top-level sections', () => {
    const docsSidebarEntries = sidebars.docsSidebar as readonly unknown[]
    const docsSidebar = docsSidebarEntries.filter(isSidebarCategoryShape)

    expect(docsSidebar).toHaveLength(8)

    const labels = docsSidebar.map((section) => section.label)

    expect(labels).toEqual([
      'Getting Started',
      'Guide',
      'CLI',
      'SDK',
      'Core',
      'Configuration',
      'Schemas',
      'Code graph',
    ])

    for (const section of docsSidebar) {
      expect(section).toMatchObject({
        type: 'category',
      })
      expect(Array.isArray(section.items)).toBe(true)
      expect(section.items.length).toBeGreaterThan(0)
    }
  })

  it('keeps nested examples grouped as child categories where the docs need hierarchy', () => {
    const docsSidebarEntries = sidebars.docsSidebar as readonly unknown[]
    const docsSidebar = docsSidebarEntries.filter(isSidebarCategoryShape)
    const findSection = (label: string): SidebarCategoryShape | undefined =>
      docsSidebar.find((section) => section.label === label)

    const coreSection = findSection('Core')
    const configurationSection = findSection('Configuration')
    const schemasSection = findSection('Schemas')

    expect(coreSection?.items).toContainEqual({
      type: 'category',
      label: 'Examples',
      items: expect.any(Array),
    })
    expect(configurationSection?.items).toContainEqual({
      type: 'category',
      label: 'Examples',
      items: expect.any(Array),
    })
    expect(schemasSection?.items).toContainEqual({
      type: 'category',
      label: 'Examples',
      items: expect.any(Array),
    })
  })

  it('groups the API sidebar by package and exported symbol kind', () => {
    expect(apiSidebars.apiSidebar).toEqual([
      'index',
      {
        type: 'category',
        label: '@specd/sdk',
        items: [
          'sdk/index',
          {
            type: 'category',
            label: 'Classes',
            items: [{ type: 'autogenerated', dirName: 'sdk/classes' }],
          },
          {
            type: 'category',
            label: 'Interfaces',
            items: [{ type: 'autogenerated', dirName: 'sdk/interfaces' }],
          },
          {
            type: 'category',
            label: 'Functions',
            items: [{ type: 'autogenerated', dirName: 'sdk/functions' }],
          },
          {
            type: 'category',
            label: 'Type Aliases',
            items: [{ type: 'autogenerated', dirName: 'sdk/type-aliases' }],
          },
          {
            type: 'category',
            label: 'Variables',
            items: [{ type: 'autogenerated', dirName: 'sdk/variables' }],
          },
        ],
      },
      {
        type: 'category',
        label: '@specd/core',
        items: [
          'core/index',
          {
            type: 'category',
            label: 'Classes',
            items: [{ type: 'autogenerated', dirName: 'core/classes' }],
          },
          {
            type: 'category',
            label: 'Interfaces',
            items: [{ type: 'autogenerated', dirName: 'core/interfaces' }],
          },
          {
            type: 'category',
            label: 'Functions',
            items: [{ type: 'autogenerated', dirName: 'core/functions' }],
          },
          {
            type: 'category',
            label: 'Type Aliases',
            items: [{ type: 'autogenerated', dirName: 'core/type-aliases' }],
          },
          {
            type: 'category',
            label: 'Variables',
            items: [{ type: 'autogenerated', dirName: 'core/variables' }],
          },
        ],
      },
      {
        type: 'category',
        label: '@specd/code-graph',
        items: [
          'code-graph/index',
          {
            type: 'category',
            label: 'Classes',
            items: [{ type: 'autogenerated', dirName: 'code-graph/classes' }],
          },
          {
            type: 'category',
            label: 'Interfaces',
            items: [{ type: 'autogenerated', dirName: 'code-graph/interfaces' }],
          },
          {
            type: 'category',
            label: 'Functions',
            items: [{ type: 'autogenerated', dirName: 'code-graph/functions' }],
          },
          {
            type: 'category',
            label: 'Type Aliases',
            items: [{ type: 'autogenerated', dirName: 'code-graph/type-aliases' }],
          },
          {
            type: 'category',
            label: 'Variables',
            items: [{ type: 'autogenerated', dirName: 'code-graph/variables' }],
          },
        ],
      },
    ])
  })
})
