import { describe, expect, it } from 'vitest'
import apiSidebars from '../../api-sidebars'
import sidebars from '../../sidebars'

interface SidebarCategoryShape {
  readonly type: 'category'
  readonly label: string
  readonly items: readonly unknown[]
}

function isSidebarCategoryShape(value: unknown): value is SidebarCategoryShape {
  if (!value || typeof value !== 'object') {
    return false
  }

  const candidate = value as Partial<SidebarCategoryShape>
  return (
    candidate.type === 'category' &&
    typeof candidate.label === 'string' &&
    Array.isArray(candidate.items)
  )
}

describe('sidebar configuration', () => {
  it('keeps the public docs sidebar organized into deliberate top-level sections', () => {
    const docsSidebarEntries = sidebars.docsSidebar as readonly unknown[]
    const docsSidebar = docsSidebarEntries.filter(isSidebarCategoryShape)

    expect(docsSidebar).toHaveLength(6)

    const labels = docsSidebar.map((section) => section.label)

    expect(labels).toEqual(['Getting Started', 'Guide', 'CLI', 'Core', 'Configuration', 'Schemas'])

    for (const section of docsSidebar) {
      expect(section).toMatchObject({
        type: 'category',
      })
      expect(Array.isArray(section.items)).toBe(true)
      expect(section.items.length).toBeGreaterThan(0)
    }
  })

  it('keeps nested examples grouped as child categories where the docs need hierarchy', () => {
    const docsSidebarEntries = sidebars.docsSidebar as readonly unknown[]
    const docsSidebar = docsSidebarEntries.filter(isSidebarCategoryShape)
    const findSection = (label: string): SidebarCategoryShape | undefined =>
      docsSidebar.find((section) => section.label === label)

    const coreSection = findSection('Core')
    const configurationSection = findSection('Configuration')
    const schemasSection = findSection('Schemas')

    expect(coreSection?.items).toContainEqual({
      type: 'category',
      label: 'Examples',
      items: expect.any(Array),
    })
    expect(configurationSection?.items).toContainEqual({
      type: 'category',
      label: 'Examples',
      items: expect.any(Array),
    })
    expect(schemasSection?.items).toContainEqual({
      type: 'category',
      label: 'Examples',
      items: expect.any(Array),
    })
  })

  it('groups the API sidebar by exported symbol kind instead of one flat list', () => {
    expect(apiSidebars.apiSidebar).toEqual([
      'index',
      {
        type: 'category',
        label: 'Classes',
        items: [{ type: 'autogenerated', dirName: 'classes' }],
      },
      {
        type: 'category',
        label: 'Interfaces',
        items: [{ type: 'autogenerated', dirName: 'interfaces' }],
      },
      {
        type: 'category',
        label: 'Functions',
        items: [{ type: 'autogenerated', dirName: 'functions' }],
      },
      {
        type: 'category',
        label: 'Type Aliases',
        items: [{ type: 'autogenerated', dirName: 'type-aliases' }],
      },
      {
        type: 'category',
        label: 'Variables',
        items: [{ type: 'autogenerated', dirName: 'variables' }],
      },
    ])
  })
})
