import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  apiSidebar: [
    'index',
    {
      type: 'category',
      label: 'Classes',
      items: [{ type: 'autogenerated', dirName: 'classes' }],
    },
    {
      type: 'category',
      label: 'Interfaces',
      items: [{ type: 'autogenerated', dirName: 'interfaces' }],
    },
    {
      type: 'category',
      label: 'Functions',
      items: [{ type: 'autogenerated', dirName: 'functions' }],
    },
    {
      type: 'category',
      label: 'Type Aliases',
      items: [{ type: 'autogenerated', dirName: 'type-aliases' }],
    },
    {
      type: 'category',
      label: 'Variables',
      items: [{ type: 'autogenerated', dirName: 'variables' }],
    },
  ],
}

export default sidebars
