import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const symbolKinds = [
  { label: 'Classes', dirName: 'classes' },
  { label: 'Interfaces', dirName: 'interfaces' },
  { label: 'Functions', dirName: 'functions' },
  { label: 'Type Aliases', dirName: 'type-aliases' },
  { label: 'Variables', dirName: 'variables' },
] as const

function buildPackageSidebar(packageId: string, packageLabel: string) {
  return {
    type: 'category' as const,
    label: packageLabel,
    items: [
      `${packageId}/index`,
      ...symbolKinds.map((kind) => ({
        type: 'category' as const,
        label: kind.label,
        items: [{ type: 'autogenerated' as const, dirName: `${packageId}/${kind.dirName}` }],
      })),
    ],
  }
}

const sidebars: SidebarsConfig = {
  apiSidebar: [
    'index',
    buildPackageSidebar('sdk', '@specd/sdk'),
    buildPackageSidebar('core', '@specd/core'),
    buildPackageSidebar('code-graph', '@specd/code-graph'),
  ],
}

export default sidebars
