import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: ['guide/what-is-specd', 'guide/index', 'guide/installation', 'guide/getting-started'],
    },
    {
      type: 'category',
      label: 'Guide',
      items: [
        'guide/code-graph',
        'guide/philosophy',
        'guide/specs',
        'guide/changes',
        'guide/project-structure',
        'guide/workflow',
        'guide/skills',
        'guide/context-compilation',
        'guide/cli',
        'guide/configuration',
        'guide/configuration-examples',
        'guide/workspaces',
        'guide/schemas',
        'guide/standard-schema',
        'guide/custom-schemas',
        'guide/selectors',
        'guide/artifacts',
        'guide/deltas',
      ],
    },
    {
      type: 'category',
      label: 'CLI',
      items: [
        'cli/index',
        'cli/guide',
        'cli/changes',
        'cli/drafts',
        'cli/discarded',
        'cli/archive',
        'cli/specs',
        'cli/project',
        'cli/schema',
        'cli/graph',
        'cli/config',
        'cli/storage',
        'cli/plugins',
        'cli/project-init',
        'cli/project-context-specs',
        'cli/project-metadata',
        'cli/project-update',
        'cli/project-update-metadata',
        'cli/spec-init',
        'cli/spec-schema',
        'cli/spec-deps',
        'cli/spec-implementation',
        'cli/spec-metadata',
        'cli/spec-generate-metadata',
        'cli/spec-optimizations',
        'cli/plugins-install',
        'cli/plugins-list',
        'cli/plugins-show',
        'cli/plugins-update',
        'cli/plugins-uninstall',
        'cli/cli-reference',
      ],
    },
    {
      type: 'category',
      label: 'Skills',
      items: ['skills/skills-template-rendering'],
    },
    {
      type: 'category',
      label: 'SDK',
      items: ['sdk/index'],
    },
    {
      type: 'category',
      label: 'Core',
      items: [
        'core/index',
        'core/overview',
        'core/domain-model',
        'core/ports',
        'core/services',
        'core/use-cases',
        'core/errors',
        {
          type: 'category',
          label: 'Examples',
          items: ['core/examples/implementing-a-port'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Schemas',
      items: [
        'schemas/schema-format',
        {
          type: 'category',
          label: 'Examples',
          items: [
            'schemas/examples/index',
            'schemas/examples/full-schema',
            'schemas/examples/delta-files',
            'schemas/examples/validations-and-delta-validations',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Code graph',
      items: ['code-graph/index', 'code-graph/use-cases', 'code-graph/services'],
    },
  ],
}

export default sidebars
